CREATE TABLE user_configuration (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED,
  `salary` INT(10) UNSIGNED NOT NULL,
  `payday` INT(30) UNSIGNED NOT NULL DEFAULT 30,
  `percentage_alert_expense` INT(3) UNSIGNED NOT NULL DEFAULT 70,
  `created_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY(user_id) REFERENCES user(id)
);
